#!/usr/bin/env node
// ROUND 5 sweep: 20 realistic queries, each ROUTED to its cheapest entry point (sym / project-brief /
// endpoints.yaml / capability-map grep / ask), measured against the raw cost (grep + read .java).
// Reports a per-query table + aggregate economy. Usage: node engine/tools/sweep-bench.mjs [root]
import { statSync, readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from '../lib/build.mjs';
import { readCache } from '../lib/cache.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const ENGINE = join(here, '..', 'thunder.mjs');
const root = process.argv[2] || join(here, '..', '..', 'demo');
const C = join(root, '.claude', 'cache', 'thunder-java');
const tok = (b) => Math.round(b / 4);
const fileTok = (...fs) => tok(fs.filter(Boolean).reduce((a, f) => { try { return a + statSync(f).size; } catch { return a; } }, 0));
const eng = (...args) => tok(Buffer.byteLength(execFileSync('node', [ENGINE, ...args, root], { maxBuffer: 1 << 24 })));
const grepTok = (file, term) => { try { return tok(Buffer.byteLength(readFileSync(file, 'utf8').split('\n').filter((l) => l.toLowerCase().includes(term.toLowerCase())).join('\n'))); } catch { return 0; } };

const { model } = build(root);
const cache = readCache(root);
const sample = [...model.contexts].sort((a, b) => b.endpoints.length - a.endpoints.length).find((c) => c.endpoints.length) || model.contexts[0];
const T = sample.types;
const svc = (T.find((t) => t.n.endsWith('Service')) || {}).n;
const ctrl = (T.find((t) => t.n.endsWith('Controller')) || {}).n;
const repo = (T.find((t) => t.n.endsWith('Repository')) || {}).n;
const entity = Object.keys(sample.entities)[0] || (T[0] || {}).n;
const moduleName = sample.module;
const cname = sample.name;
const abs = (rel) => join(root, rel);
const allJava = model.contexts.flatMap((c) => c.files.map(abs));
const controllers = allJava.filter((p) => p.endsWith('Controller.java'));
const sampleController = sample.files.map(abs).filter((p) => p.endsWith('Controller.java'));
const moduleControllers = model.contexts.filter((c) => c.module === moduleName).flatMap((c) => c.files.map(abs)).filter((p) => p.endsWith('Controller.java'));
const defFile = (n) => { for (const c of model.contexts) for (const t of c.types) if (t.n === n) return abs(t.file); return null; };
const refFiles = (n) => {
  const out = [];
  const re = new RegExp(`\\b${n}\\b`);
  for (const f of cache.values()) {
    const hay = (f.types || []).flatMap((t) => [t.ext, ...(t.methods || []).map((m) => m.sig), ...(t.fields || []).map((x) => x.t)]).filter(Boolean).join(' ');
    if (re.test(hay)) out.push(abs(f.file));
  }
  return out;
};
const BRIEF = join(C, 'project-brief.yaml');
const EPS = join(C, 'endpoints.yaml');
const CAP = join(C, 'capability-map.yaml');

// ≥50 diverse queries, generated by iterating over every entity (service / controller / repository /
// class / module / context) so the set scales with the codebase. Each routed to its cheapest entry
// point (sym · brief · endpoints · capability-map grep · ask) vs the raw cost (read/grep .java).
const types = [...new Set(model.contexts.flatMap((c) => c.types.map((t) => t.n)))];
const services = types.filter((n) => n.endsWith('Service'));
const controllers2 = types.filter((n) => n.endsWith('Controller'));
const repos = types.filter((n) => n.endsWith('Repository'));
const otherTypes = types.filter((n) => !/(Service|Controller|Repository)$/.test(n));
const ctxList = [...model.contexts].sort((a, b) => b.endpoints.length - a.endpoints.length);
const cnames = [...new Set(ctxList.map((c) => c.name))];
const ctxFiles = (n) => (ctxList.find((c) => c.name === n) || sample).files.map(abs);
// Evenly sample at most n entities so the query count stays ~60 (≥50) and the run is fast even on a
// huge codebase (bigdemo = 3840 types), while still spreading questions across the whole project.
const even = (arr, n) => { if (arr.length <= n) return arr; const out = []; for (let i = 0; i < n; i++) out.push(arr[Math.floor((i * arr.length) / n)]); return [...new Set(out)]; };
const Q = [];
Q.push(['architecture overview', 'brief', () => fileTok(BRIEF), () => fileTok(...allJava)]);
Q.push(['which modules exist', 'brief', () => fileTok(BRIEF), () => fileTok(...allJava)]);
Q.push(['how is the app structured', 'brief', () => fileTok(BRIEF), () => fileTok(...allJava)]);
Q.push(['list all endpoints', 'endpoints', () => fileTok(EPS), () => fileTok(...controllers)]);
const refd = (n) => refFiles(n).length > 0; // only entities actually referenced somewhere
for (const s of even(services, 10)) {
  Q.push([`where is ${s} defined`, 'sym', () => eng('sym', 'def', s), () => fileTok(defFile(s))]);
  Q.push([`what does ${s} do`, 'ask', () => eng('ask', '--facts', s), () => fileTok(defFile(s))]);
}
for (const s of even(services.filter(refd), 10)) Q.push([`callers of ${s}`, 'sym', () => eng('sym', 'refs', s), () => fileTok(...refFiles(s))]);
for (const c of even(controllers2, 8)) {
  Q.push([`find the ${c} class`, 'sym', () => eng('sym', 'def', c), () => fileTok(defFile(c))]);
  Q.push([`endpoints of ${c}`, 'endpoints', () => grepTok(EPS, c.replace(/Controller$/, '')), () => fileTok(defFile(c))]);
}
for (const r of even(repos.filter(refd), 5)) Q.push([`who uses ${r}`, 'sym', () => eng('sym', 'refs', r), () => fileTok(...refFiles(r))]);
for (const t of even(otherTypes, 8)) Q.push([`where is ${t} defined`, 'sym', () => eng('sym', 'def', t), () => fileTok(defFile(t))]);
for (const n of even(cnames, 8)) {
  Q.push([`who handles ${n}`, 'discovery', () => grepTok(CAP, n), () => fileTok(...allJava)]);
  Q.push([`business rules for ${n}`, 'ask', () => eng('ask', '--facts', n + ' validation'), () => fileTok(...ctxFiles(n))]);
  Q.push([`flow of creating ${n}`, 'ask', () => eng('ask', n + ' create flow'), () => fileTok(...ctxFiles(n))]);
  Q.push([`how does ${n} work`, 'ask', () => eng('ask', n), () => fileTok(...ctxFiles(n))]);
}

if (!existsSync(BRIEF)) { console.error('build the index first'); process.exit(1); }
if (Q.length < 50) console.error(`# note: only ${Q.length} queries (small project; ≥50 needs a realistic codebase like bigdemo)`);
console.log(`# sweep-bench (root=${root}, ${Q.length} routed queries)\n`);
console.log('| # | Query | route | thunder | raw | factor | winner |');
console.log('|---|---|---|---|---|---|---|');
let sumA = 0, sumB = 0, wins = 0;
Q.forEach(([q, route, A, B], i) => {
  const a = A(), b = B();
  sumA += a; sumB += b;
  const win = a <= b;
  if (win) wins++;
  console.log(`| ${i + 1} | ${q} | ${route} | ${a} | ${b} | ${b && a ? (b / a).toFixed(1) + '×' : '—'} | ${win ? 'thunder' : 'raw'} |`);
});
const economy = Math.round((1 - sumA / sumB) * 100);
const winPct = Math.round((wins / Q.length) * 100);
console.log(`\nthunder wins **${wins}/${Q.length}** (${winPct}%) · aggregate **${sumA} vs ${sumB} tok → ${economy}% saved** (targets ≥70% wins, ≥70% saved).`);
process.exit(winPct >= 70 && economy >= 70 ? 0 : 1);
