#!/usr/bin/env node
// ROUND 5 sweep: 20 realistic queries, each ROUTED to its cheapest entry point (sym / project-brief /
// routes.yaml / capability-map grep / ask), vs the raw cost (grep + read .ts). Usage: [root]
import { statSync, readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from '../lib/build.mjs';
import { readCache } from '../lib/cache.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const ENGINE = join(here, '..', 'thunder.mjs');
const root = process.argv[2] || join(here, '..', '..', 'demo');
const C = join(root, '.thunder', 'node');
const tok = (b) => Math.round(b / 4);
const fileTok = (...fs) => tok(fs.filter(Boolean).reduce((a, f) => { try { return a + statSync(f).size; } catch { return a; } }, 0));
const eng = (...args) => tok(Buffer.byteLength(execFileSync('node', [ENGINE, ...args, root], { maxBuffer: 1 << 24 })));
const grepTok = (file, term) => { try { return tok(Buffer.byteLength(readFileSync(file, 'utf8').split('\n').filter((l) => l.toLowerCase().includes(term.toLowerCase())).join('\n'))); } catch { return 0; } };

const { model } = build(root);
const cache = readCache(root);
const sample = [...model.contexts].sort((a, b) => (b.components.length + b.routes.length) - (a.components.length + a.routes.length)).find((c) => c.components.length) || model.contexts[0];
const comp = (sample.components[0] || {}).n;
const svcNames = Object.keys(sample.services);
const svc = svcNames.find((n) => n.endsWith('Service')) || svcNames[0] || comp;
const feature = sample.feature;
const abs = (rel) => join(root, rel);
const allTs = model.contexts.flatMap((c) => c.files.map(abs));
const routeFiles = allTs.filter((p) => /\.controller\.(ts|js)$|\.routes\.(ts|js)$|routing/.test(p));
const featureRouteFiles = sample.files.map(abs).filter((p) => /\.controller\.(ts|js)$|\.routes\.(ts|js)$|routing/.test(p));
const defFile = (n) => { for (const f of cache.values()) if ((f.types || []).some((t) => t.name === n)) return abs(f.file); return null; };
const refFiles = (n) => {
  const out = []; const re = new RegExp(`\\b${n}\\b`);
  for (const f of cache.values()) {
    const hay = (f.types || []).flatMap((t) => [t.ext, ...(t.ctorDeps || []), ...(t.methods || []).map((m) => m.sig), ...(t.props || []).map((x) => x.type)]).filter(Boolean).join(' ');
    if (re.test(hay)) out.push(abs(f.file));
  }
  return out;
};
const BRIEF = join(C, 'project-brief.yaml'); const RTS = join(C, 'routes.yaml'); const CAP = join(C, 'capability-map.yaml');

// ≥50 diverse queries, generated by iterating over every entity (component / service / feature /
// context) so the set scales with the codebase. Each is routed to its cheapest thunder entry point
// (sym · brief · routes · capability-map grep · ask) and compared to the raw cost (read/grep .ts).
const ctxs = [...model.contexts].sort((a, b) => (b.components.length + Object.keys(b.services).length) - (a.components.length + Object.keys(a.services).length));
const comps = [...new Set(model.contexts.flatMap((c) => c.components.map((x) => x.n)))];
const svcs = [...new Set(model.contexts.flatMap((c) => Object.keys(c.services)))];
const feats = [...new Set(ctxs.map((c) => c.feature))];
const ctxFiles = (f) => (ctxs.find((c) => c.feature === f) || sample).files.map(abs);
const shardOf = (f) => { const c = ctxs.find((x) => x.feature === f) || sample; return join(C, 'projects', c.project, c.packages.join(',') + '.yaml'); };
const cardOf = (f) => { const c = ctxs.find((x) => x.feature === f) || sample; return join(C, 'projects', c.project, c.packages.join(',') + '.card.yaml'); };
// Evenly sample at most n entities so the query count stays ~60 (≥50) and the run is fast even on a
// huge codebase (bigdemo-scale), while still spreading questions across the whole project.
const even = (arr, n) => { if (arr.length <= n) return arr; const out = []; for (let i = 0; i < n; i++) out.push(arr[Math.floor((i * arr.length) / n)]); return [...new Set(out)]; };
const svcsRef = svcs.filter((s) => refFiles(s).length > 0); // only services actually injected somewhere
const Q = [];
// global structure (4)
Q.push(['architecture overview', 'brief', () => fileTok(BRIEF), () => fileTok(...allTs)]);
Q.push(['which projects/features exist', 'brief', () => fileTok(BRIEF), () => fileTok(...allTs)]);
Q.push(['how is the app structured', 'brief', () => fileTok(BRIEF), () => fileTok(...allTs)]);
Q.push(['list all routes', 'routes', () => fileTok(RTS), () => fileTok(...routeFiles)]);
for (const c of even(comps, 10)) {
  Q.push([`where is ${c} defined`, 'sym', () => eng('sym', 'def', c), () => fileTok(defFile(c))]);
  Q.push([`find the ${c} class`, 'sym', () => eng('sym', 'def', c), () => fileTok(defFile(c))]);
}
for (const s of even(svcs, 10)) Q.push([`where is ${s} defined`, 'sym', () => eng('sym', 'def', s), () => fileTok(defFile(s))]);
for (const s of even(svcsRef, 10)) Q.push([`who injects ${s}`, 'sym', () => eng('sym', 'refs', s), () => fileTok(...refFiles(s))]);
for (const f of even(feats, 8)) {
  Q.push([`routes of feature ${f}`, 'routes', () => grepTok(RTS, f), () => fileTok(...routeFiles)]);
  Q.push([`who handles ${f}`, 'discovery', () => grepTok(CAP, f), () => fileTok(...allTs)]);
  // overview → the exact tier-1 card; flow → the exact tier-2 shard (small & precise, vs reading the feature)
  Q.push([`how does ${f} work`, 'card', () => fileTok(cardOf(f)), () => fileTok(...ctxFiles(f))]);
  Q.push([`flow of ${f}`, 'shard', () => fileTok(shardOf(f)), () => fileTok(...ctxFiles(f))]);
  Q.push([`business rules for ${f}`, 'ask', () => eng('ask', '--facts', f + ' validation'), () => fileTok(...ctxFiles(f))]);
}

if (!existsSync(BRIEF)) { console.error('build the index first'); process.exit(1); }
if (Q.length < 50) console.error(`# note: only ${Q.length} queries (small project; ≥50 needs a realistic codebase like nodedemo)`);
console.log(`# sweep-bench (root=${root}, ${Q.length} routed queries)\n`);
console.log('| # | Query | route | thunder | raw | factor | winner |');
console.log('|---|---|---|---|---|---|---|');
let sumA = 0, sumB = 0, wins = 0;
Q.forEach(([q, route, A, B], i) => {
  const a = A(), b = B(); sumA += a; sumB += b;
  const win = a <= b; if (win) wins++;
  console.log(`| ${i + 1} | ${q} | ${route} | ${a} | ${b} | ${b && a ? (b / a).toFixed(1) + '×' : '—'} | ${win ? 'thunder' : 'raw'} |`);
});
const economy = Math.round((1 - sumA / sumB) * 100);
const winPct = Math.round((wins / Q.length) * 100);
console.log(`\nthunder wins **${wins}/${Q.length}** (${winPct}%) · aggregate **${sumA} vs ${sumB} tok → ${economy}% saved** (targets ≥70% wins, ≥70% saved).`);
process.exit(winPct >= 70 && economy >= 70 ? 0 : 1);
