#!/usr/bin/env node
// ROUND 5 sweep: 20 realistic queries, each ROUTED to its cheapest entry point (sym / project-brief /
// routes.yaml / capability-map grep / ask), vs the raw cost (grep + read .py). Usage: [root]
import { statSync, readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from '../lib/build.mjs';
import { readCache } from '../lib/cache.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const ENGINE = join(here, '..', 'thunder.mjs');
const root = process.argv[2] || join(here, '..', '..', 'demo');
const C = join(root, '.thunder', 'python');
const tok = (b) => Math.round(b / 4);
const fileTok = (...fs) => tok(fs.filter(Boolean).reduce((a, f) => { try { return a + statSync(f).size; } catch { return a; } }, 0));
const eng = (...args) => tok(Buffer.byteLength(execFileSync('node', [ENGINE, ...args, root], { maxBuffer: 1 << 24 })));
const grepTok = (file, term) => { try { return tok(Buffer.byteLength(readFileSync(file, 'utf8').split('\n').filter((l) => l.toLowerCase().includes(term.toLowerCase())).join('\n'))); } catch { return 0; } };

const { model } = build(root);
const cache = readCache(root);
const sample = [...model.contexts].sort((a, b) => b.routes.length - a.routes.length).find((c) => c.routes.length && c.classes.length) || model.contexts[0];
const cls = (sample.classes.find((c) => c.n.endsWith('Service')) || sample.classes[0] || {}).n;
const mdl = Object.keys(sample.models)[0] || cls;
const feature = sample.name;
const abs = (rel) => join(root, rel);
const allPy = model.contexts.flatMap((c) => c.files.map(abs));
const routeFiles = allPy.filter((p) => /routes\.py$|urls\.py$|views\.py$/.test(p));
const featureRouteFiles = sample.files.map(abs).filter((p) => /routes\.py$|urls\.py$|views\.py$/.test(p));
const defFile = (n) => { for (const f of cache.values()) { if ((f.types || []).some((t) => t.name === n) || (f.functions || []).some((fn) => fn.name === n)) return abs(f.file); } return null; };
const refFiles = (n) => {
  const out = []; const re = new RegExp(`\\b${n}\\b`);
  for (const f of cache.values()) {
    const hay = [...(f.types || []).flatMap((t) => [...t.bases, ...(t.methods || []).map((m) => m.sig)]), ...(f.functions || []).flatMap((fn) => [fn.sig, ...(fn.deps || [])])].join(' ');
    if (re.test(hay)) out.push(abs(f.file));
  }
  return out;
};
const BRIEF = join(C, 'project-brief.yaml'); const RTS = join(C, 'routes.yaml'); const CAP = join(C, 'capability-map.yaml'); const ANALYZE = join(here, 'analyze.mjs');

// ≥50 diverse queries, generated by iterating over every entity (class / service / model / route /
// package) so the set scales with the codebase. Each routed to its cheapest entry point
// (sym · brief · routes · capability-map grep · analyze · ask) vs the raw cost (read/grep .py).
const classes = [...new Set(model.contexts.flatMap((c) => (c.classes || []).map((x) => x.n)))];
const services = classes.filter((n) => n.endsWith('Service'));
const models2 = [...new Set(model.contexts.flatMap((c) => Object.keys(c.models || {})))];
const otherClasses = classes.filter((n) => !services.includes(n));
const ctxList = [...model.contexts].sort((a, b) => b.routes.length - a.routes.length);
const feats = [...new Set(ctxList.map((c) => c.name))];
const ctxFiles = (n) => (ctxList.find((c) => c.name === n) || sample).files.map(abs);
// Evenly sample at most n entities so the query count stays ~60 (≥50) and the run is fast even on a
// huge codebase, while still spreading questions across the whole project.
const even = (arr, n) => { if (arr.length <= n) return arr; const out = []; for (let i = 0; i < n; i++) out.push(arr[Math.floor((i * arr.length) / n)]); return [...new Set(out)]; };
const Q = [];
Q.push(['architecture overview', 'brief', () => fileTok(BRIEF), () => fileTok(...allPy)]);
Q.push(['which frameworks/projects', 'brief', () => fileTok(BRIEF), () => fileTok(...allPy)]);
Q.push(['how is the app structured', 'brief', () => fileTok(BRIEF), () => fileTok(...allPy)]);
Q.push(['list all routes', 'routes', () => fileTok(RTS), () => fileTok(...routeFiles)]);
Q.push(['mutating routes / attack surface', 'analyze', () => tok(Buffer.byteLength(execFileSync('node', [ANALYZE, root], { maxBuffer: 1 << 24 }))), () => fileTok(...routeFiles)]);
const refd = (n) => refFiles(n).length > 0; // only entities actually referenced somewhere
for (const c of even(otherClasses, 10)) Q.push([`where is ${c} defined`, 'sym', () => eng('sym', 'def', c), () => fileTok(defFile(c))]);
for (const c of even(otherClasses.filter(refd), 8)) Q.push([`who uses ${c}`, 'sym', () => eng('sym', 'refs', c), () => fileTok(...refFiles(c))]);
for (const s of even(services, 8)) {
  Q.push([`where is ${s} defined`, 'sym', () => eng('sym', 'def', s), () => fileTok(defFile(s))]);
  Q.push([`what does ${s} do`, 'ask', () => eng('ask', '--facts', s), () => fileTok(defFile(s))]);
}
for (const s of even(services.filter(refd), 8)) Q.push([`uses of ${s}`, 'sym', () => eng('sym', 'refs', s), () => fileTok(...refFiles(s))]);
for (const m of even(models2, 6)) Q.push([`find the ${m} model`, 'sym', () => eng('sym', 'def', m), () => fileTok(defFile(m))]);
for (const f of even(feats, 8)) {
  Q.push([`routes of ${f}`, 'routes', () => grepTok(RTS, f), () => fileTok(...routeFiles)]);
  Q.push([`who handles ${f}`, 'discovery', () => grepTok(CAP, f), () => fileTok(...allPy)]);
  Q.push([`flow of creating ${f}`, 'ask', () => eng('ask', f + ' create flow'), () => fileTok(...ctxFiles(f))]);
  Q.push([`how does ${f} work`, 'ask', () => eng('ask', f), () => fileTok(...ctxFiles(f))]);
  Q.push([`business rules for ${f}`, 'ask', () => eng('ask', '--facts', f + ' validation'), () => fileTok(...ctxFiles(f))]);
}

if (!existsSync(BRIEF)) { console.error('build the index first'); process.exit(1); }
if (Q.length < 50) console.error(`# note: only ${Q.length} queries (small project; ≥50 needs a realistic codebase like pydemo)`);
console.log(`# sweep-bench (root=${root}, ${Q.length} routed queries)\n`);
console.log('| # | Query | route | thunder | raw | factor | winner |');
console.log('|---|---|---|---|---|---|---|');
let sumA = 0, sumB = 0, wins = 0;
Q.forEach(([q, route, A, B], i) => {
  const a = A(), b = B(); sumA += a; sumB += b;
  const win = a <= b; if (win) wins++;
  console.log(`| ${i + 1} | ${q} | ${route} | ${a} | ${b} | ${b && a ? (b / a).toFixed(1) + '×' : '—'} | ${win ? 'thunder' : 'raw'} |`);
});
const economy = Math.round((1 - sumA / sumB) * 100);
const winPct = Math.round((wins / Q.length) * 100);
console.log(`\nthunder wins **${wins}/${Q.length}** (${winPct}%) · aggregate **${sumA} vs ${sumB} tok → ${economy}% saved** (targets ≥70% wins, ≥70% saved).`);
process.exit(winPct >= 70 && economy >= 70 ? 0 : 1);
